name: CI Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v5

    # Setup Node With Matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # NPM INSTALL
    - name: npm-install
      run: npm ci

    # NPM BUILD
    - name: npm-Build
      run: npm run build

    # Package Artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{ matrix.node-version }}
        path: |
          ${{ github.workspace }}/build/*
